<?php

namespace AppBundle\Repository;

/**
 * json_dataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class json_dataRepository extends \Doctrine\ORM\EntityRepository
{
}
